//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students_db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students_And_Classes
    {
        public int StudentClassID { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Grade { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Students Students { get; set; }
    }
}
